version: "3.6"

services:
 hosting_webapp:
  image: node:19.2.0-alpine3.15
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 redis:
  image: redis:7.2.3-alpine
  restart: always
  labels:
   - "promtail=true"

 hosting:
  image: golang:1.21.5
  stop_grace_period: 1m
  volumes:
   - ".:/data"
   - "go_dir:/go"
   - "go_cache:/.cache"
  environment:
   - LOGLEVEL=debug
   - BASEURL=http://localhost:8080
   - COOKIE_PATH=/
   - COOKIE_SECURE=false
   - CSRF_KEY=my-csrf-key
   - JWT_KEY=my-jwt-key
   - LOG_STREAM_KEY=my-stream-key
   - LOG_STREAM_DIR=/data/logs
   - WEBDEV=true
   - ENABLE_WORKER=true
   - INITIAL_BALANCE=350
   - REDIS_URL=redis:6379
  env_file:
   - .env
  depends_on:
   - redis
  ports:
   - "8080:8080"
  working_dir: /data
  command: ["go", "run", "."]

volumes:
  go_dir: {}
  go_cache: {}
