version: "3.6"

services:
 hosting_webapp:
  image: node:19.2.0-alpine3.15
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 hosting:
  image: golang:1.20.7
  stop_grace_period: 1m
  volumes:
   - ".:/data"
   - "go_cache:/go"
  environment:
   - LOGLEVEL=debug
   - BASEURL=http://localhost:8080
   - COOKIE_DOMAIN=localhost
   - COOKIE_PATH=/
   - COOKIE_SECURE=false
   - CSRF_KEY=my-csrf-key
   - JWT_KEY=my-jwt-key
   - LOG_STREAM_KEY=my-stream-key
   - LOG_STREAM_DIR=/data/logs
   - WEBDEV=true
   - ENABLE_WORKER=true
  env_file:
    - .env
  ports:
   - "8080:8080"
  working_dir: /data
  command: ["go", "run", "."]

volumes:
  go_cache: {}
