version: "3.6"

services:
 hosting:
  image: golang:1.20.7
  volumes:
   - ".:/data"
   - "go_cache:/go"
  environment:
   - LOGLEVEL=debug
   - BASEURL=http://localhost:8080
   - COOKIE_DOMAIN=localhost
   - COOKIE_PATH=/
   - COOKIE_SECURE=false
   - CSRF_KEY=my-csrf-key
   - JWT_KEY=my-jwt-key
   - WEBDEV=true
   - ENABLE_WORKER=true
  env_file:
    - .env
  ports:
   - "8080:8080"
  working_dir: /data
  command: ["go", "run", "."]

volumes:
  go_cache: {}
