version: "3.7"

services:
 ui-{{.ServerShortID}}:
  image: ghcr.io/minetest-go/mtui:{{.MTUIVersion}}
  networks:
   - terminator
   - network-{{.ServerShortID}}
  environment:
   COOKIE_DOMAIN: "{{.Hostname}}"
   COOKIE_SECURE: "true"
   LOGLEVEL: debug
   WORLD_DIR: "/root/.minetest/worlds/world"
   SERVER_NAME: "{{.Servername}}"
   ENABLE_FEATURES: "shell,luashell,minetest_config,docker,modmanagement"
   MINETEST_CONFIG: "/minetest.conf"
   DOCKER_HOSTNAME: "ui-{{.ServerShortID}}"
   DOCKER_MINETEST_CONFIG: "{{.BaseDir}}/minetest.conf"
   DOCKER_MINETEST_PORT: {{.Port}}
   DOCKER_NETWORK: "network-{{.ServerShortID}},terminator"
   DOCKER_WORLD_DIR: "{{.BaseDir}}/world"
   DOCKER_MINETEST_CONTAINER: "{{.Enginename}}"
  volumes:
   - "./world:/root/.minetest/worlds/world"
   - "./world/minetest.conf:/minetest.conf"
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.{{.ServerShortID}}.rule=Host(`{{.Hostname}}`)"
    - "traefik.http.services.{{.ServerShortID}}.loadbalancer.server.port=8080"
    - "traefik.http.routers.{{.ServerShortID}}.entrypoints=websecure"
    - "traefik.http.routers.{{.ServerShortID}}.tls.certresolver=default"
  restart: always

networks:
 terminator:
  external: true
 network-{{.ServerShortID}}:
  external: true