version: "3.7"

services:
 ui-{{.ServerShortID}}:
  image: ghcr.io/minetest-go/mtui:{{.Server.UIVersion}}
  networks:
   - terminator
   - network-{{.ServerShortID}}
  environment:
   COOKIE_DOMAIN: "{{.Hostname}}"
   COOKIE_PATH: "/ui/"
   COOKIE_SECURE: "true"
   JWT_KEY: "{{.Server.JWTKey}}"
   LOGLEVEL: debug
   LOG_STREAM_URL: "{{.Config.BaseURL}}/api/logstream/{{.Server.ID}}"
   LOG_STREAM_AUTHORIZATION: "{{.Config.LogStreamKey}}"
   WORLD_DIR: "/root/.minetest/worlds/world"
   SERVER_NAME: "{{.Server.Name}}"
   INSTALL_MTUI_MOD: "true"
   ENABLE_FEATURES: "shell,luashell,minetest_config,docker,modmanagement,mediaserver,signup,chat"
   MINETEST_CONFIG: "/minetest.conf"
   GEOIP_API: "https://hosting.minetest.ch/api/geoip"
   DEFAULT_THEME: "flatly"
   DOCKER_HOSTNAME: "ui-{{.ServerShortID}}"
   DOCKER_MINETEST_CONFIG: "{{.BaseDir}}/world/minetest.conf"
   DOCKER_MINETEST_PORT: {{.Server.Port}}
   DOCKER_NETWORK: "network-{{.ServerShortID}},terminator"
   DOCKER_WORLD_DIR: "{{.BaseDir}}/world"
   DOCKER_CONTAINER_PREFIX: "{{.ServerShortID}}"
  volumes:
   - "./world:/root/.minetest/worlds/world"
   - "./world/minetest.conf:/minetest.conf"
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.services.{{.ServerShortID}}.loadbalancer.server.port=8080"
    - "traefik.http.routers.{{.ServerShortID}}.rule=Host(`{{.Hostname}}`) && PathPrefix(`/ui`)"
    - "traefik.http.routers.{{.ServerShortID}}.entrypoints=websecure"
    - "traefik.http.routers.{{.ServerShortID}}.tls.certresolver=default"
    - "traefik.http.routers.{{.ServerShortID}}.middlewares={{.ServerShortID}}-stripprefix"
    - "traefik.http.middlewares.{{.ServerShortID}}-stripprefix.stripprefix.prefixes=/ui"
  restart: always

 nginx-{{.ServerShortID}}:
  image: nginx:1.25.2
  networks:
   - terminator
   - network-{{.ServerShortID}}
  restart: always
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.services.{{.ServerShortID}}-nginx.loadbalancer.server.port=80"
    - "traefik.http.routers.{{.ServerShortID}}-nginx.rule=Host(`{{.Hostname}}`)"
    - "traefik.http.routers.{{.ServerShortID}}-nginx.entrypoints=websecure"
    - "traefik.http.routers.{{.ServerShortID}}-nginx.tls.certresolver=default"
  volumes:
   - "./nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./world/www:/www"

networks:
 terminator:
  external: true
 network-{{.ServerShortID}}:
  external: true