# example matterbridge config with libera example
# Docs:
# * custom config: https://github.com/42wim/matterbridge/wiki/How-to-create-your-config
# * all settings: https://github.com/42wim/matterbridge/wiki/Settings

[irc]
[irc.Libera]
Server="irc.libera.chat:6667"
Nick="hosting-bot-{{.ServerShortID}}"
Password="change-me"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
ColorNicks=true
JoinDelay=2000

#[discord]
#[discord.Discord]
#Token="<discord_token>"
#Server="<discord_server_id>"
#RemoteNickFormat="[{BRIDGE}] <{NICK}> "
#UseUserName=false
#AllowMention=["users"]

[api.luanti]
BindAddress="0.0.0.0:4242"
Token="my-token"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#luanti-hosting"
#[[gateway.inout]]
#account = "discord.Discord"
#channel="main"
[[gateway.inout]]
account="api.luanti"
channel="api"