name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest docker image
        run: |
          docker build . -t ghcr.io/minetest-hosting/mt-hosting-manager:latest
          docker push ghcr.io/minetest-hosting/mt-hosting-manager:latest

      - name: Trigger deployment on hosting.minetest.ch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy
          repo: minetest-hosting/hosting.minetest.ch
          ref: refs/heads/main
          token: ${{ secrets.GH_DEPLOY_TOKEN }}
